# Generated by Django 4.2 on 2023-04-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
