# Generated by Django 4.2 on 2023-04-19 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_comment_options_community_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
