# Generated by Django 4.2 on 2023-04-28 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_body_alter_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
