# Generated by Django 4.2 on 2023-04-28 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
    ]
