# Generated by Django 4.2 on 2023-04-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_comment_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
